library(shiny)
library(bslib)
library(shinyjs)
library(ggplot2)
library(plotly)
library(grid)
library(gridExtra)
library(readxl)
library(ggpattern)
library(scales)
library(dplyr)
library(tidyr)
library(purrr)
library(magrittr)

source("R/main_ui.R")
source("R/main_server.R")
source("R/run_app.R")

run_plate_reader_app()
